version: '3'

tasks:
  new:
    desc: "Create a new contest directory using acc."
    cmds:
      - acc new {{.CLI_ARGS}}

  test:
    desc: "Test the solution in the current directory using oj."
    cmds:
      - |
        if [ -f main.go ]; then
          oj test -c "go run main.go"
        elif [ -f Cargo.toml ]; then
          oj test -c "cargo run"
        else
          echo "No go or rust files found."
          exit 1
        fi

  submit:
    desc: "Submit the solution in the current directory using acc."
    cmds:
      - |
        if [ -f main.go ]; then
          acc submit main.go
        elif [ -f Cargo.toml ]; then
          acc submit
        else
          echo "No go or rust files found."
          exit 1
        fi
